// Die Fragenstapel. Jede Frage ergaenzt den Satz „Wer von euch …?" und muss
// sich deshalb auf eine *Person in der Runde* beantworten lassen – nicht auf
// eine Meinung, nicht auf ein Ja/Nein.
//
// Alle Texte sind selbst geschrieben, aus keiner Anleitung und keiner App
// abgetippt. Spielregeln sind frei, fremde Fragenlisten nicht.
//
// Zwei Stapel, beide ohne Alkohol, Sex und Koerperliches – dieses Spiel soll
// bewusst ohne die 18+-Maschinerie aus „Ich hab noch nie" auskommen:
//
//   HARMLOS  laesst sich am Familientisch vorlesen
//   FRECH    zielt auf Macken und Peinlichkeiten, bleibt aber jugendfrei

export const HARMLOS = [
  "würde bei einem Stromausfall zuerst die Kerzen finden?",
  "kennt den Weg, ohne aufs Handy zu schauen?",
  "würde sich im eigenen Wohnviertel verlaufen?",
  "hat die meisten ungelesenen Nachrichten?",
  "steht morgens zuletzt auf?",
  "redet am längsten, ohne Luft zu holen?",
  "würde ein Möbelstück ohne Anleitung zusammenbauen?",
  "hätte danach Schrauben übrig?",
  "vergisst am ehesten, wo das Fahrrad steht?",
  "würde einen Kuchen backen, ohne zu wiegen?",
  "kann am besten Grimassen schneiden?",
  "hat als Kind am häufigsten geschummelt?",
  "würde bei einer Quizshow zuerst rausfliegen?",
  "würde die Quizshow gewinnen?",
  "hört dieselbe Musik seit zehn Jahren?",
  "kennt den Text von jedem Lied im Radio?",
  "singt am lautesten falsch mit?",
  "würde einen ganzen Tag schweigen können?",
  "packt den Koffer erst am Abend vor der Reise?",
  "hätte im Koffer drei Paar Schuhe zu viel?",
  "verpasst am ehesten den Zug?",
  "steht eine Stunde zu früh am Bahnsteig?",
  "würde sich bei einer Wanderung zuerst hinsetzen?",
  "läuft bergauf noch schneller?",
  "hat die ordentlichste Wohnung?",
  "räumt erst auf, wenn Besuch kommt?",
  "würde ein Tier adoptieren, ohne vorher zu fragen?",
  "redet mit Pflanzen?",
  "kann am besten Geschichten erfinden?",
  "würde beim Schachspiel am längsten überlegen?",
  "gewinnt jedes Brettspiel und tut so, als wäre es Zufall?",
  "wirft beim Verlieren fast das Brett um?",
  "hat den seltsamsten Kühlschrankinhalt?",
  "isst Reste noch am dritten Tag?",
  "kocht ohne Rezept und trifft es genau?",
  "würde ein Restaurant nach dem Brot beurteilen?",
  "bestellt immer dasselbe?",
  "probiert alles einmal?",
  "wäre in einem Film die ruhige Nebenrolle?",
  "hätte im Film die beste letzte Zeile?",
  "würde bei einem Umzug am meisten schleppen?",
  "würde beim Umzug die Kisten falsch beschriften?",
  "findet in jeder Stadt sofort ein Café?",
  "hat die längste Liste mit Dingen, die man mal machen sollte?",
  "hakt auf der Liste tatsächlich etwas ab?",
  "würde freiwillig eine Rede halten?",
  "würde vorher heimlich verschwinden?",
  "erklärt Dinge am besten?",
  "erklärt Dinge am längsten?",
  "merkt sich jeden Geburtstag?",
  "gratuliert drei Tage zu spät?",
  "hat die meisten Fotos auf dem Handy?",
  "hat davon keins je angeschaut?",
  "würde bei Regen trotzdem rausgehen?",
  "sagt am ehesten kurzfristig ab?",
  "ist immer zuerst da?",
  "hat den besten Sitzplatz-Instinkt im Zug?",
  "liest die Bedienungsanleitung wirklich?",
  "drückt einfach auf alle Knöpfe?",
  "würde sich einen Bart wachsen lassen, nur um zu sehen, wie es aussieht?",
  "hat die meisten angefangenen und nie beendeten Bücher?",
  "liest das Ende zuerst?",
  "würde bei einem Gewitter auf den Balkon gehen?",
  "hat die beste Handschrift?",
  "schreibt Einkaufszettel und lässt sie zu Hause liegen?",
  "kauft im Supermarkt drei Dinge, die nicht auf dem Zettel standen?",
  "würde ein Instrument neu lernen?",
  "würde nach zwei Wochen aufhören?",
  "kann am besten pfeifen?",
  "hat den ansteckendsten Lacher?",
  "lacht über die eigenen Witze am meisten?",
  "erzählt denselben Witz zum dritten Mal?",
  "würde bei einem Karaokeabend zuerst ans Mikro gehen?",
  "kennt die meisten unnützen Fakten?",
  "würde in der Wüste am längsten durchhalten?",
  "würde sich zuerst über den Sonnenbrand beschweren?",
  "hätte bei einem Roadtrip das Steuer und würde es nicht abgeben?",
  "schläft im Auto sofort ein?",
  "hat die beste Playlist für lange Fahrten?",
  "verliert am ehesten den Haustürschlüssel?",
  "hat einen Ersatzschlüssel an drei Orten deponiert?",
];

export const FRECH = [
  "googelt heimlich die anderen aus dieser Runde?",
  "hat schon mal so getan, als wäre das Handy leer, um nicht zu antworten?",
  "checkt beim Essen zuerst, wie das Foto aussieht?",
  "hat den peinlichsten Suchverlauf?",
  "hat die meisten Ausreden auf Lager?",
  "würde beim Kartenspiel schummeln und es abstreiten?",
  "hat schon mal eine Serie heimlich allein weitergeschaut?",
  "liest Nachrichten und antwortet erst am nächsten Tag?",
  "hat die längste Sprachnachricht der Runde verschickt?",
  "hört Sprachnachrichten auf doppelter Geschwindigkeit?",
  "hat schon mal jemanden mit falschem Namen angesprochen?",
  "erkennt Leute nicht wieder, die man letzte Woche zusammen getroffen hat?",
  "tut so, als wäre der Film längst gesehen?",
  "gibt am schnellsten zu, unrecht zu haben?",
  "gibt es nie zu?",
  "hat als Kind am längsten an eine offensichtliche Lüge geglaubt?",
  "würde bei einem Streit zuerst einlenken?",
  "würde noch drei Tage später darauf zurückkommen?",
  "hat die dramatischste Art, krank zu sein?",
  "sagt „bin gleich da“ und braucht noch vierzig Minuten?",
  "ist heimlich am kompetitivsten?",
  "würde ein Gruppenfoto löschen, weil das eigene Gesicht nicht passt?",
  "postet das Foto trotzdem?",
  "hat in dieser Runde die meisten Geheimnisse?",
  "würde ein Geheimnis am schnellsten weitererzählen?",
  "kann am schlechtesten lügen?",
  "kann es erschreckend gut?",
  "hat schon mal etwas kaputtgemacht und nichts gesagt?",
  "leiht sich Dinge aus und bringt sie nie zurück?",
  "führt darüber innerlich Buch?",
  "würde bei einer Wette am weitesten gehen?",
  "würde die Wette am nächsten Tag bestreiten?",
  "redet im Schlaf?",
  "hat den unaufgeräumtesten Rucksack?",
  "trägt seit Jahren dasselbe Lieblingsstück auf?",
  "kauft Dinge, nur weil sie im Angebot sind?",
  "hat die meisten ungenutzten Abos?",
  "vergisst am ehesten den Namen einer Person mitten im Gespräch?",
  "schaut beim Reden auf das Handy?",
  "würde zuerst einschlafen, wenn alle noch reden?",
  "beendet den Abend und geht dann doch nicht?",
  "schickt nachts um drei Nachrichten?",
  "stellt sieben Wecker und verschläft trotzdem?",
  "singt unter der Dusche ganze Konzerte?",
  "übt Gespräche vorher im Kopf?",
  "sagt dann etwas völlig anderes?",
  "hat die stärkste Meinung zu etwas völlig Belanglosem?",
  "würde stundenlang über Serien diskutieren?",
  "hat den unerwartetsten Lieblingsfilm?",
  "würde bei einem Wettessen gewinnen und es bereuen?",
];

export const MODI = ["harmlos", "gemischt", "frech"];

/** Der Stapel, aus dem in diesem Modus gezogen wird. */
export function stapelFuer(modus) {
  if (modus === "harmlos") return HARMLOS.slice();
  if (modus === "frech") return FRECH.slice();
  return [...HARMLOS, ...FRECH];
}
