// Die Fragenstapel. Jede Frage ergaenzt den Satz „Wer von euch …?" und muss
// sich deshalb auf eine *Person in der Runde* beantworten lassen – nicht auf
// eine Meinung, nicht auf ein Ja/Nein.
//
// Alle Texte sind selbst geschrieben, aus keiner Anleitung und keiner App
// abgetippt. Spielregeln sind frei, fremde Fragenlisten nicht.
//
// Drei Stapel:
//
//   HARMLOS    laesst sich am Familientisch vorlesen
//   FRECH      Macken, Peinlichkeiten, unangenehme Wahrheiten – aber ohne
//              Alkohol, Sex und Koerperliches, also weiter jugendfrei
//   SCHMUTZIG  ab 18: Sex, Kink, Rausch, Betrug, Dinge, die man erlebt und
//              nie erzaehlt. Nur ueber den Modus `ab18` erreichbar, und der
//              haengt hinter derselben Abfrage wie der 18+-Stapel in
//              „Ich hab noch nie"
//
// Warum der dritte Stapel Archetypen abklappert statt nur Themen: das Spiel
// zeigt auf *Personen*. Eine Frage trifft nur, wenn am Tisch jemand sitzt, auf
// den sie passt. Deshalb ist SCHMUTZIG bewusst nach Menschentypen gebaut – die
// Stillen, die Lauten, die Gleichgueltigen, die chronisch Onlinen, die mit dem
// Spiegelfoto – und nicht als eine lange Reihe Sexfragen. Wer sonst nie
// gewaehlt wird, wird hier gewaehlt.

export const HARMLOS = [
  "würde bei einem Stromausfall zuerst die Kerzen finden?",
  "kennt den Weg, ohne aufs Handy zu schauen?",
  "würde sich im eigenen Wohnviertel verlaufen?",
  "hat die meisten ungelesenen Nachrichten?",
  "steht morgens zuletzt auf?",
  "redet am längsten, ohne Luft zu holen?",
  "würde ein Möbelstück ohne Anleitung zusammenbauen?",
  "hätte danach Schrauben übrig?",
  "vergisst am ehesten, wo das Fahrrad steht?",
  "würde einen Kuchen backen, ohne zu wiegen?",
  "kann am besten Grimassen schneiden?",
  "hätte als Kind am häufigsten geschummelt?",
  "würde bei einer Quizshow zuerst rausfliegen?",
  "würde die Quizshow gewinnen?",
  "hört dieselbe Musik seit zehn Jahren?",
  "kennt den Text von jedem Lied im Radio?",
  "singt am lautesten falsch mit?",
  "würde einen ganzen Tag schweigen können?",
  "packt den Koffer erst am Abend vor der Reise?",
  "hätte im Koffer drei Paar Schuhe zu viel?",
  "verpasst am ehesten den Zug?",
  "steht eine Stunde zu früh am Bahnsteig?",
  "würde sich bei einer Wanderung zuerst hinsetzen?",
  "läuft bergauf noch schneller?",
  "hat die ordentlichste Wohnung?",
  "räumt erst auf, wenn Besuch kommt?",
  "würde ein Tier adoptieren, ohne vorher zu fragen?",
  "redet mit Pflanzen?",
  "kann am besten Geschichten erfinden?",
  "würde beim Schachspiel am längsten überlegen?",
  "gewinnt jedes Brettspiel und tut so, als wäre es Zufall?",
  "wirft beim Verlieren fast das Brett um?",
  "hat den seltsamsten Kühlschrankinhalt?",
  "isst Reste noch am dritten Tag?",
  "kocht ohne Rezept und trifft es genau?",
  "würde ein Restaurant nach dem Brot beurteilen?",
  "bestellt immer dasselbe?",
  "probiert alles einmal?",
  "wäre in einem Film die ruhige Nebenrolle?",
  "hätte im Film die beste letzte Zeile?",
  "würde bei einem Umzug am meisten schleppen?",
  "würde beim Umzug die Kisten falsch beschriften?",
  "findet in jeder Stadt sofort ein Café?",
  "hat die längste Liste mit Dingen, die man mal machen sollte?",
  "hakt auf der Liste tatsächlich etwas ab?",
  "würde freiwillig eine Rede halten?",
  "würde vorher heimlich verschwinden?",
  "erklärt Dinge am besten?",
  "erklärt Dinge am längsten?",
  "merkt sich jeden Geburtstag?",
  "gratuliert drei Tage zu spät?",
  "hat die meisten Fotos auf dem Handy?",
  "hat davon keins je angeschaut?",
  "würde bei Regen trotzdem rausgehen?",
  "sagt am ehesten kurzfristig ab?",
  "ist immer zuerst da?",
  "hat den besten Sitzplatz-Instinkt im Zug?",
  "liest die Bedienungsanleitung wirklich?",
  "drückt einfach auf alle Knöpfe?",
  "würde sich einen Bart wachsen lassen, nur um zu sehen, wie es aussieht?",
  "hat die meisten angefangenen und nie beendeten Bücher?",
  "liest das Ende zuerst?",
  "würde bei einem Gewitter auf den Balkon gehen?",
  "hat die beste Handschrift?",
  "schreibt Einkaufszettel und lässt sie zu Hause liegen?",
  "kauft im Supermarkt drei Dinge, die nicht auf dem Zettel standen?",
  "würde ein Instrument neu lernen?",
  "würde nach zwei Wochen aufhören?",
  "kann am besten pfeifen?",
  "hat den ansteckendsten Lacher?",
  "lacht über die eigenen Witze am meisten?",
  "erzählt denselben Witz zum dritten Mal?",
  "würde bei einem Karaokeabend zuerst ans Mikro gehen?",
  "kennt die meisten unnützen Fakten?",
  "würde in der Wüste am längsten durchhalten?",
  "würde sich zuerst über den Sonnenbrand beschweren?",
  "hätte bei einem Roadtrip das Steuer und würde es nicht abgeben?",
  "schläft im Auto sofort ein?",
  "hat die beste Playlist für lange Fahrten?",
  "verliert am ehesten den Haustürschlüssel?",
  "hat einen Ersatzschlüssel an drei Orten deponiert?",
];

export const FRECH = [
  "googelt heimlich die anderen aus dieser Runde?",
  "tut am ehesten so, als wäre das Handy leer, um nicht zu antworten?",
  "checkt beim Essen zuerst, wie das Foto aussieht?",
  "hat den peinlichsten Suchverlauf?",
  "hat die meisten Ausreden auf Lager?",
  "würde beim Kartenspiel schummeln und es abstreiten?",
  "schaut die Serie am ehesten heimlich allein weiter?",
  "liest Nachrichten und antwortet erst am nächsten Tag?",
  "hat die längste Sprachnachricht der Runde verschickt?",
  "hört Sprachnachrichten auf doppelter Geschwindigkeit?",
  "spricht jemanden am ehesten mit dem falschen Namen an und zieht es durch?",
  "erkennt Leute nicht wieder, die man letzte Woche zusammen getroffen hat?",
  "tut so, als wäre der Film längst gesehen?",
  "gibt am schnellsten zu, unrecht zu haben?",
  "gibt es nie zu?",
  "hätte als Kind am längsten an eine offensichtliche Lüge geglaubt?",
  "würde bei einem Streit zuerst einlenken?",
  "würde noch drei Tage später darauf zurückkommen?",
  "hat die dramatischste Art, krank zu sein?",
  "sagt „bin gleich da“ und braucht noch vierzig Minuten?",
  "ist heimlich am kompetitivsten?",
  "würde ein Gruppenfoto löschen, weil das eigene Gesicht nicht passt?",
  "postet das Foto trotzdem?",
  "hat in dieser Runde die meisten Geheimnisse?",
  "würde ein Geheimnis am schnellsten weitererzählen?",
  "kann am schlechtesten lügen?",
  "kann es erschreckend gut?",
  "würde am ehesten etwas kaputtmachen und nichts sagen?",
  "leiht sich Dinge aus und bringt sie nie zurück?",
  "führt darüber innerlich Buch?",
  "würde bei einer Wette am weitesten gehen?",
  "würde die Wette am nächsten Tag bestreiten?",
  "redet im Schlaf?",
  "hat den unaufgeräumtesten Rucksack?",
  "trägt seit Jahren dasselbe Lieblingsstück auf?",
  "kauft Dinge, nur weil sie im Angebot sind?",
  "hat die meisten ungenutzten Abos?",
  "vergisst am ehesten den Namen einer Person mitten im Gespräch?",
  "schaut beim Reden auf das Handy?",
  "würde zuerst einschlafen, wenn alle noch reden?",
  "beendet den Abend und geht dann doch nicht?",
  "schickt nachts um drei Nachrichten?",
  "stellt sieben Wecker und verschläft trotzdem?",
  "singt unter der Dusche ganze Konzerte?",
  "übt Gespräche vorher im Kopf?",
  "sagt dann etwas völlig anderes?",
  "hat die stärkste Meinung zu etwas völlig Belanglosem?",
  "würde stundenlang über Serien diskutieren?",
  "hat den unerwartetsten Lieblingsfilm?",
  "würde bei einem Wettessen gewinnen und es bereuen?",

  // Die Stillen
  "würde am ehesten so tun, als wäre niemand zu Hause, obwohl das Licht brennt?",
  "übt vor einem Anruf den ersten Satz?",
  "geht von einer Feier, ohne sich zu verabschieden?",
  "würde einen Umweg gehen, um niemanden grüßen zu müssen?",
  "sagt zu und hofft insgeheim, dass es abgesagt wird?",
  "steht auf jeder Feier in der Küche, weil dort weniger los ist?",
  "hat für jede Einladung denselben fertigen Ausredensatz?",
  "kennt nach acht Jahren die Namen der Nachbarn nicht?",
  "drückt einen Anruf weg und schreibt danach, gerade keine Zeit gehabt zu haben?",
  "würde am ehesten ohne Bestellung wieder gehen, weil zu viele Leute da sind?",
  "wartet, bis der Flur leer ist, bevor die Wohnungstür aufgeht?",
  "freut sich am meisten, wenn ein Treffen abgesagt wird?",

  // Die Lauten
  "hat den kürzesten Weg von ruhig zu laut?",
  "würde bei einem Streit im Straßenverkehr aussteigen?",
  "würde am ehesten etwas werfen und behaupten, es sei gefallen?",
  "schreibt Nachrichten, die man besser nicht abschickt, und schickt sie ab?",
  "hebt eine Beleidigung drei Jahre lang auf?",
  "wird zuerst persönlich, wenn eine Diskussion eng wird?",
  "würde am ehesten eine Tür so zuschlagen, dass etwas herunterfällt?",
  "würde sich beim Freundschaftsspiel mit dem Schiedsrichter anlegen?",
  "hat den lockersten Finger auf der Hupe?",
  "beendet einen Streit, indem einfach lauter geredet wird?",

  // Die Gleichgültigen
  "sagt, es sei egal, und meint es tatsächlich?",
  "hat noch nie jemanden zurückgerufen?",
  "würde beim Feueralarm den Kaffee austrinken?",
  "würde eine Beziehung am ehesten in der Mittagspause per Nachricht beenden?",
  "findet Geburtstage grundsätzlich übertrieben?",
  "antwortet auf eine schlechte Nachricht mit einem Schulterzucken?",
  "kommt zu spät und entschuldigt sich nicht?",
  "hat noch nie eine Frist ernst genommen?",

  // Vor der Kamera
  "braucht für ein Foto am längsten und sagt, es sei zufällig entstanden?",
  "kennt das beste Licht in jedem Raum sofort?",
  "hat mehr Fotos von sich als von allen anderen zusammen?",
  "löscht ein Bild wieder, wenn zu wenig Reaktionen kommen?",
  "schaut sofort nach, wer eine Story zuerst gesehen hat?",
  "postet etwas, damit genau eine Person es sieht?",
  "würde für ein Bild am ehesten auf ein Geländer steigen?",
  "hat den größten Unterschied zwischen Profil und Wohnzimmer?",
  "stellt das Essen um, bevor jemand essen darf?",

  // Im Film
  "wäre im Horrorfilm zuerst tot?",
  "wäre die Person, die vorschlägt, sich aufzuteilen?",
  "würde nachsehen gehen, was im Keller so komisch klingt?",
  "wäre im Raubzug der Teil der Gruppe, der zu viel redet?",
  "wäre der Bösewicht, der die ganze Zeit über nett war?",
  "würde in einer Apokalypse zuerst gebissen, weil da noch jemand zu retten war?",
  "würde die Gruppe für ein warmes Bett verraten?",
  "wäre in der Liebeskomödie die Person, die zum Flughafen rennt?",
  "wäre die Person, die am Flughafen nicht mehr wartet?",
  "würde im Katastrophenfilm zuerst das Handy herausholen?",
  "wäre der Nebencharakter, an den sich am Ende alle erinnern?",
  "würde im Verhör als Erstes reden?",

  // Was wirklich passiert
  "würde am ehesten weinen und es auf Allergien schieben?",
  "lässt eine Freundschaft am ehesten ohne Streit einfach auslaufen?",
  "sucht am ehesten nach jemandem, den man seit zehn Jahren nicht gesehen hat?",
  "würde auf einer Beerdigung am ehesten lachen?",
  "würde ein Geschenk am ehesten an die Person weiterverschenken, von der es kam?",
  "erfindet am ehesten eine Krankheit, um abzusagen?",
  "würde am ehesten etwas finden und lieber nicht nachfragen?",
  "schaut jemandem beim Reden ins Gesicht und denkt an etwas völlig anderes?",
  "würde jemandem am ehesten eine Entscheidung ausreden und sich später darüber freuen?",
  "mag ein Haustier heimlich lieber als die meisten Menschen?",
  "würde am ehesten etwas mitnehmen, das nicht bezahlt ist?",
  "würde im Vorstellungsgespräch am ehesten etwas erfinden?",
  "würde jemanden am ehesten ausladen, weil jemand Besseres zugesagt hat?",
  "gönnt anderen den Erfolg am wenigsten und sagt es nie?",
];


/**
 * Ab 18. Alkohol, Sex, Kink, Betrug – und die Sorte Frage, auf die man am Tisch
 * jemanden zeigen kann, ohne dass es je jemand zugeben wuerde.
 *
 * Erreichbar nur ueber den Modus `ab18`, und der haengt hinter einer Abfrage
 * (siehe `public/app.js`). Voreingestellt ist weiterhin `gemischt`, und weder
 * `harmlos` noch `frech` noch `gemischt` fassen diesen Stapel je an.
 *
 * Auch hier gilt die Hausregel: geschlechtsneutral. Die Frage zeigt auf eine
 * echte Person am Tisch; ein „er“ oder „sie“ traefe jedes Mal jemanden falsch.
 */
export const SCHMUTZIG = [
  // Direkt
  "würde am ehesten einen Dildo bis zum Anschlag nehmen und nach mehr fragen?",
  "würde am ehesten mitten am Tag in einer Umkleide rangehen?",
  "schaut beim Sex am ehesten in den Spiegel statt zur anderen Person?",
  "würde am ehesten in einem Videocall unter dem Tisch weitermachen?",
  "würde am ehesten die Nachbarn wecken und morgens im Treppenhaus freundlich grüßen?",
  "würde am ehesten mit jemandem schlafen, nur um dem Ex eins auszuwischen?",
  "würde am ehesten dem besten Freund den Partner ausspannen?",
  "denkt auf einer Beerdigung am ehesten an Sex?",
  "würde am ehesten auf einer Familienfeier im Gästeklo rangehen?",
  "würde am ehesten für Geld mit jemandem schlafen, den hier alle kennen?",
  "würde am ehesten drei Leute an einem Wochenende durchziehen und keinen Namen behalten?",
  "würde am ehesten ein Sextape drehen und die Datei nicht löschen?",
  "würde das Sextape am ehesten in die Familiengruppe schicken?",
  "würde am ehesten mit einem Kollegen anfangen und es der ganzen Abteilung erzählen?",
  "würde am ehesten mit dem Vermieter schlafen, um die Miete zu drücken?",
  "hat den größten Pornokonsum und die sauberste Fassade?",
  "holt sich am ehesten in einer fremden Wohnung einen runter?",
  "würde sich am ehesten auf einer Party im Bad einen runterholen und danach normal weiterreden?",
  "schläft am ehesten mittendrin ein?",
  "greift mittendrin am ehesten nach dem Handy?",
  "sagt am ehesten laut den falschen Namen und nennt es hinterher einen Kosenamen?",
  "würde am ehesten mit jemandem schlafen, den man nicht attraktiv findet, nur aus Neugier?",
  "würde am ehesten dem eigenen Chef ein Bild schicken?",
  "wäre in einem Swingerclub am ehesten nach zehn Minuten heimisch?",
  "würde dort am ehesten in der Ecke stehen und alles kommentieren?",
  "kommt am ehesten in unter zwei Minuten und nennt es Absicht?",
  "geht danach am ehesten sofort duschen und sagt nichts?",
  "würde am ehesten mit dem Ex von jemandem aus dieser Runde schlafen?",
  "denkt dabei am ehesten an jemanden aus dieser Runde?",
  "würde am ehesten ohne Vorwarnung dritte Personen dazuholen?",

  // Härter
  "würde am ehesten Maske und Handschuhe auspacken, bevor überhaupt jemand gefragt hat?",
  "würde am ehesten jemanden fesseln und den Knoten nicht mehr aufbekommen?",
  "würde am ehesten eine ganze Nacht nur Anweisungen geben?",
  "hätte am ehesten kniend die beste Zeit des Lebens?",
  "würde am ehesten darum betteln, geschlagen zu werden?",
  "würde am ehesten zuschlagen, ohne zu fragen?",
  "würde am ehesten eine Leine tragen und behaupten, das sei Mode?",
  "würde eine Wohnung am ehesten nach der Zahl der befestigbaren Punkte aussuchen?",
  "würde am ehesten mit verbundenen Augen einsteigen, ohne zu wissen, wer im Raum ist?",
  "würde am ehesten fremde Füße anfassen und Geld dafür verlangen?",
  "würde am ehesten dafür bezahlen, angeschrien zu werden?",
  "würde ein Safeword am ehesten in der ersten Minute brauchen?",
  "würde ein Safeword am ehesten aus Stolz nie benutzen?",
  "würde am ehesten in Frauenkleidern rausgehen und den Abend genießen?",
  "würde in Frauenkleidern am ehesten besser aussehen als alle anderen hier?",
  "hätte am ehesten die eigene Sammlung offen im Regal stehen?",
  "weiß beim Wort Klinikspiel am ehesten sofort, was gemeint ist?",
  "würde am ehesten drei Stunden vorbereiten für zwanzig Minuten Ergebnis?",
  "würde am ehesten mit dem Nachbarn tauschen, nur um zu sehen, wie das ist?",
  "hätte am ehesten einen Fetisch, bei dem hier alle kurz still werden?",

  // Ekel
  "würde sich am ehesten für Geld die Arschhaare flechten lassen?",
  "würde am ehesten dafür bezahlen, dass es jemand anderes tut?",
  "riecht abends am schlimmsten und merkt es selbst nicht?",
  "pisst am ehesten in der Dusche und findet die Frage überflüssig?",
  "würde am ehesten fremde Zehennägel schneiden, wenn genug Geld dabei ist?",
  "würde am ehesten ungefragt einen Pickel auf einem fremden Rücken ausdrücken?",
  "würde das am ehesten genießen?",
  "hat die schlimmste Zahnbürste in dieser Runde?",
  "würde am ehesten drei Wochen dieselbe Bettwäsche behalten und Besuch empfangen?",
  "würde am ehesten in einem vollen Fahrstuhl furzen und niemanden ansehen?",
  "würde es am ehesten zugeben?",
  "würde am ehesten etwas vom Boden essen, das schon jemand angefasst hat?",
  "trinkt am ehesten ein fremdes Glas aus?",
  "würde am ehesten in eine Flasche pissen, statt aufzustehen?",
  "hätte am ehesten Schimmel im Kühlschrank, den man beim Namen nennen kann?",
  "würde am ehesten eine Woche ohne Duschen durchhalten und normal zur Arbeit gehen?",
  "würde am ehesten in ein fremdes Waschbecken kotzen und es dort lassen?",
  "würde am ehesten nicht spülen, weil es gerade unbequem ist?",
  "zieht am ehesten ein Haar aus dem Essen und isst weiter?",
  "würde am ehesten die Zehennägel im Wohnzimmer schneiden, mit Gästen im Raum?",
  "hat die meisten Flecken auf der Matratze und die beste Erklärung dafür?",
  "würde am ehesten vor Publikum einen Rotz an die Hauswand schnippen?",
  "begutachtet am ehesten das Ohrenschmalz, bevor es weggewischt wird?",
  "würde am ehesten im Freibad ins Wasser pissen und dabei lächeln?",
  "würde am ehesten fremde Unterwäsche anziehen, wenn keine eigene da ist?",

  // Rausch
  "würde am ehesten nehmen, was ein Fremder auf der Hand liegen hat?",
  "würde am ehesten dicht zur Arbeit gehen und den Tag durchziehen?",
  "sagt am häufigsten, es sei alles im Griff?",
  "würde am ehesten auf einer Hochzeit im Klo neben der Oma etwas ziehen?",
  "setzt die eigene Grenze am ehesten bei fünf Tagen wach an?",
  "würde am ehesten Pilze nehmen und dann allein spazieren gehen?",
  "würde am ehesten mischen, was man nicht mischen soll?",
  "würde am ehesten den Krankenwagen rufen und dabei selbst nicht ansprechbar sein?",
  "würde am ehesten für eine Nacht das halbe Konto verbrennen?",
  "hält am längsten durch und erinnert sich am wenigsten?",
  "wäre am ehesten mit dem Dealer befreundet und lädt ihn zum Geburtstag ein?",
  "würde am ehesten den Medikamentenschrank der Eltern plündern?",
  "würde am ehesten nüchtern behaupten, nie etwas genommen zu haben?",
  "schläft am ehesten auf einer Clubtoilette ein?",
  "macht am nächsten Morgen am ehesten direkt weiter?",
  "würde am ehesten allein zu Hause anfangen?",
  "würde am ehesten für den Rausch die Beziehung aufgeben?",
  "fängt auf Ketamin am ehesten eine Grundsatzdiskussion an?",
  "hätte am Flughafen am ehesten etwas im Schuh?",
  "würde am ehesten den Zoll ansprechen, bevor der Zoll fragt?",

  // Straftaten
  "würde am ehesten ein Kilo Gras über die Grenze fahren?",
  "würde dabei am ehesten so schwitzen, dass alles auffliegt?",
  "würde am ehesten die eigene Bude anzünden, wenn die Versicherung stimmt?",
  "nimmt am ehesten Schwarzgeld an und schimpft weiter über Steuern?",
  "würde am ehesten eine Unterschrift fälschen, ohne lange nachzudenken?",
  "würde am ehesten ein Fahrrad mitnehmen, das nicht abgeschlossen ist?",
  "würde am ehesten im Supermarkt etwas in die Jacke stecken und es lustig finden?",
  "würde am ehesten Bürgergeld beziehen und daneben schwarz arbeiten?",
  "würde am ehesten das eigene Geschwisterkind anzeigen?",
  "würde in einer Vernehmung am ehesten sofort alles erzählen?",
  "würde am ehesten alles abstreiten, obwohl es Videos gibt?",
  "würde am ehesten falsch aussagen, um jemanden aus dieser Runde zu decken?",
  "würde am ehesten betrunken fahren, weil es ja nur zehn Minuten sind?",
  "würde ohne Führerschein am ehesten trotzdem weiterfahren?",
  "würde am ehesten eine Wohnung besetzen und Vorhänge aufhängen?",
  "würde am ehesten einen Automaten aufbrechen, wenn niemand hinsieht?",
  "würde aus einem gefundenen Portemonnaie am ehesten einen Schein nehmen und den Rest abgeben?",
  "würde am ehesten den eigenen Chef erpressen, wenn etwas in der Hand liegt?",
  "hinterzieht am ehesten Steuern und erzählt es beim Abendessen?",
  "würde am ehesten für Geld eine falsche Identität annehmen?",
  "würde am ehesten die Kasse im eigenen Laden anzapfen?",
  "hätte im Knast am ehesten nach einer Woche Freunde?",
  "hätte dort am ehesten am ersten Tag Probleme?",
  "würde am ehesten den Notruf missbrauchen, um etwas durchzusetzen?",
  "würde hier am Tisch am ehesten eine Straftat gestehen, nach der niemand gefragt hat?",

  // Gewalt
  "würde am ehesten zuerst zuschlagen und danach fragen?",
  "fängt am ehesten eine Schlägerei an, die man nicht gewinnen kann?",
  "würde am ehesten danebenstehen und filmen?",
  "würde am ehesten mit einer Flasche zurückkommen?",
  "würde für jemanden aus dieser Runde am ehesten ins Krankenhaus gehen?",
  "würde am ehesten weglaufen und es später als Sieg erzählen?",
  "wirft dem Partner im Streit am ehesten etwas hinterher?",
  "würde den Nachbarn wegen der Musik am ehesten körperlich angehen?",
  "würde am ehesten aus Prinzip ein fremdes Auto zerkratzen?",
  "würde am ehesten eine Tür eintreten, statt zu klingeln?",
  "steigt im Straßenverkehr am ehesten aus, bevor der Motor aus ist?",
  "führt den Streit am ehesten noch weiter, wenn alle anderen längst gegangen sind?",

  // Unter Freunden
  "wäre in der Schule eher der Täter als das Opfer gewesen?",
  "würde am ehesten ein Geheimnis aus dieser Runde weitererzählen, für eine gute Pointe?",
  "würde am ehesten jemanden hier fallen lassen, sobald es unbequem wird?",
  "würde am ehesten die Beerdigung von jemandem hier verpassen, weil etwas dazwischenkommt?",
  "lästert am ehesten über jemanden, der zwei Meter weiter steht?",
  "würde am ehesten eine Freundschaft für Geld beenden?",
  "über wen wird hier am meisten geredet, wenn er nicht dabei ist?",
  "würde am ehesten jemanden aus dieser Runde beim Chef anschwärzen?",
  "würde am ehesten den Partner von jemandem hier auf einen Fehltritt hinweisen und es genießen?",
  "würde am ehesten jemanden hier bloßstellen, nur weil es lustig wäre?",
  "würde am ehesten eine Gruppe spalten, ohne dass es jemand merkt?",
  "stellt den eigenen Erfolg am ehesten über die Freundschaft?",
  "würde jemanden von hier am ehesten vergessen, wenn er ein Jahr wegzieht?",
  "würde in einer Notlage am ehesten niemanden von hier anrufen?",
  "wechselt im Streit am ehesten auf die Seite, die gewinnt?",
  "würde ein Unglück von jemandem hier am ehesten in einer Story verwerten?",
  "empfindet am meisten Schadenfreude, wenn hier jemand scheitert?",
  "würde am ehesten aus einer Gruppe austreten und nie sagen, warum?",
  "würde den Erfolg von jemandem hier am ehesten kleinreden, sobald er den Raum verlässt?",
  "würde am ehesten aus Neid etwas kaputtmachen?",

  // Familie
  "würde die eigenen Eltern am ehesten ohne Zögern ins Heim geben?",
  "fängt den Erbstreit am ehesten an, bevor die Beerdigung vorbei ist?",
  "würde ein Geschwisterkind am ehesten komplett aus dem Leben streichen?",
  "würde der Familie am ehesten Geld schulden und es aussitzen?",
  "würde am ehesten die eigene Familie beklauen und die Schuld dem Handwerker geben?",
  "würde am ehesten mit den Eltern brechen und sich gut dabei fühlen?",
  "würde am ehesten ein Kind bekommen, um jemanden zu halten?",
  "würde Weihnachten am ehesten absagen, ohne jemandem Bescheid zu sagen?",
  "würde den eigenen Vater am ehesten beim Finanzamt melden?",
  "würde am ehesten das Erbe verzocken?",
  "würde die Eltern am ehesten belügen, bis sie sterben?",
  "erzählt der Familie am ehesten nie, was hier gespielt wurde?",

  // Geld und Fassade
  "lügt beim Gehalt am ehesten nach oben?",
  "würde am ehesten den Lebenslauf komplett erfinden?",
  "würde für ein teures Auto am ehesten in Schulden gehen?",
  "pumpt am ehesten Freunde an und zahlt nie zurück?",
  "rechnet beim Trinkgeld am genauesten und redet am meisten über Großzügigkeit?",
  "würde am ehesten eine Beziehung wegen des Geldes anfangen?",
  "würde am ehesten reich werden und sich hier nie wieder melden?",
  "würde am ehesten pleitegehen und es niemandem sagen?",
  "würde am ehesten alles in eine Währung stecken, die ein Bekannter empfohlen hat?",
  "würde am ehesten in einem Schneeballsystem landen und andere nachziehen?",
  "würde für Geld am ehesten alle hier verraten?",
  "würde die eigene Wohnung am ehesten untervermieten, während der Vermieter danebensteht?",
  "gibt am meisten aus und hat am wenigsten?",
  "hätte am ehesten ein Konto in einem anderen Land?",

  // Selbstbetrug
  "belügt sich hier am meisten selbst?",
  "würde am ehesten ernsthaft an eine Verschwörung glauben und Vorträge halten?",
  "hatte die peinlichste politische Phase und redet sie klein?",
  "würde am ehesten einer Sekte beitreten, weil dort nette Leute sind?",
  "würde am ehesten alles wegwerfen und für sechs Wochen in einem Van leben?",
  "bräuchte am ehesten eine Therapie und liest stattdessen ein Buch?",
  "erklärt anderen die Welt und versteht die eigene am wenigsten?",
  "erklärt Dating auf dem Papier und bekommt es im Leben nicht hin?",
  "kennt den eigenen Marktwert auf zwei Kommastellen?",
  "sucht die Schuld am ehesten immer bei den anderen?",
  "wäre am ehesten aus Prinzip gegen etwas, das man gar nicht kennt?",
  "würde am ehesten heiraten, nur um es hinter sich zu haben?",
  "würde am ehesten einen Namen tätowieren, der nicht hält?",
  "benutzt mit fünfzig am ehesten noch dieselbe Ausrede?",
  "hält sich für den Normalsten hier und ist es am wenigsten?",

  // Bildschirm
  "hat die meisten offenen Tabs, die niemand sehen darf?",
  "würde am ehesten ein falsches Profil anlegen, um jemanden zu beobachten?",
  "würde am ehesten jemanden aus dieser Runde durchleuchten?",
  "hat den privaten Modus praktisch als Startseite?",
  "würde am ehesten für Bilder Geld verlangen?",
  "würde am ehesten dafür bezahlen?",
  "würde am ehesten ein OnlyFans starten und es hier verschweigen?",
  "würde damit am ehesten wirklich Geld verdienen?",
  "würde am ehesten mit einer künstlichen Intelligenz flirten und es ernst meinen?",
  "macht in einem Kommentarstreit am ehesten die Nacht durch?",
  "würde das eigene Handy vor einer Kontrolle am ehesten ins Klo werfen?",
  "würde das Handy am ehesten jedem in die Hand geben?",
  "würde am ehesten ein fremdes Nacktbild weiterschicken?",
  "verschickt das eigene am ehesten ungefragt?",
  "wischt am ehesten weiter, während jemand mitten im Satz ist?",
  "würde die ganze Chronik löschen, sobald eine bestimmte Person mitliest?",

  // Dieselben Typen, nur nachts
  "ist am Tisch am leisesten und zu Hause am lautesten?",
  "würde am ehesten jahrelang nichts sagen und dann alles auf einmal?",
  "würde am ehesten in einer WG wohnen und niemanden dort kennen?",
  "fängt am ehesten einen Streit an, nur damit versöhnt werden muss?",
  "wirft im Streit am ehesten mit dem Wort Schluss?",
  "würde am ehesten schreien, wo alle anderen flüstern?",
  "würde in einer Katastrophe am ehesten nur mit den Schultern zucken?",
  "würde eine Trennung am ehesten in der Mittagspause per Sprachnachricht erledigen?",
  "würde beim Feueralarm am ehesten den Kaffee austrinken?",
  "würde ein Date am ehesten nach dem Hintergrund für Fotos aussuchen?",
  "würde für ein Bild am ehesten etwas Gefährliches machen?",
  "hat mehr Spiegel als Fenster?",
  "würde am ehesten etwas posten, um genau einer Person wehzutun?",
  "würde das eigene Schlafzimmer am ehesten für Fotos umräumen?",
  "würde am ehesten mittendrin unterbrechen, um ein Foto zu machen?",
  "erklärt auch im Bett noch Dinge, die niemand wissen will?",
  "würde aus einer Nacht am ehesten eine Podcastfolge machen?",
  "würde am ehesten mit einem Fremden mitgehen, ohne nach dem Namen zu fragen?",
  "würde dabei am ehesten den eigenen Namen erfinden?",
  "würde eine Affäre am ehesten allen erzählen außer der Person, die es angeht?",

  // Wenn es hart auf hart kommt
  "wäre im Porno die Rolle, die man überspringt?",
  "würde am ehesten für wenig Geld in einem Erotikfilm mitspielen?",
  "würde dabei am ehesten den Text vergessen?",
  "wäre im Krimi die Affäre, durch die alles auffliegt?",
  "wäre die Person, an der die Ehe im Film zerbricht?",
  "würde in einer Zombieapokalypse am ehesten Leute gegen Vorräte tauschen?",
  "würde die eigene Gruppe am ehesten aussperren, um selbst drinnen zu sein?",
  "würde in einem Krieg am ehesten überlaufen?",
  "wäre im Gefängnisfilm die Person, die alles besorgen kann?",
  "wäre die Figur, die alle wollen und niemand behalten kann?",
  "würde am ehesten eine Sekte gründen, die tatsächlich funktioniert?",
  "würde dieser Sekte am ehesten beitreten?",
  "würde die letzten Stunden vor dem Weltuntergang am ehesten allein verbringen?",
  "bekäme die Szene, die man mit den Eltern nicht schauen kann?",
];

export const MODI = ["harmlos", "gemischt", "frech", "ab18"];

/** Der Stapel, aus dem in diesem Modus gezogen wird. */
export function stapelFuer(modus) {
  if (modus === "harmlos") return HARMLOS.slice();
  if (modus === "frech") return FRECH.slice();
  // `ab18` zieht ausschliesslich aus SCHMUTZIG. Wer den Modus einstellt, will
  // genau diese Fragen – nicht jede dritte Runde eine ueber Einkaufszettel.
  if (modus === "ab18") return SCHMUTZIG.slice();
  return [...HARMLOS, ...FRECH];
}
